### ISSUE TITLE
:|

### ISSUE THREAD

**Issue by Zirak** [JavaScriptRoom/JSHP#2]
:|

**Comment by Zirak** [comment]
@MadaraUchiha :|

**Comment by benjamingr** [comment]
@Zirak  :|

**Comment by RUJodan** [comment]
@benjamingr :|

**Comment by rlemon** [comment]
@rlemon :|

**Comment by phenomnomnominal** [comment]
:| 

(This repo ruined my nights sleep with notifications that I wasn't conscious enough to turn off :disappointed:)

**Comment by Canop** [comment]
:| 

@phenomnomnominal  are you awake yet ?

**Comment by awalgarg** [comment]
oh c'mon it is not that bad! it is odd and funny for sure, but could still be great.

p.s. sorry for all the emails. I was doing this on a personal account repo initially, but madara said doing it here would be better. I am ok with reverting if the notifications are too spammy.

**Comment by ssube** [comment]
:|

**Comment by Zirak** [comment]
:|

**Comment by benjamingr** [comment]
```
      ∩＿＿＿∩
     |ノ      ヽ
    /   ●    ● | Zirak Stahp, you're making Awal cry ──！！
   |     (_●_) ミ
  彡､     |∪|  ､｀＼
/ ＿＿    ヽノ /´>   )
(＿＿＿）     /  (_／
  |        /
  |   ／＼  ＼
  | /     )   )
   ∪     （   ＼
           ＼＿)
```

**Comment by awalgarg** [comment]
just checking...

edit: cool stuff
